/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface V3Interface extends ethers.utils.Interface {
  functions: {
    "fund()": FunctionFragment;
    "getConversionRate(uint256)": FunctionFragment;
    "getLatestRoundData()": FunctionFragment;
    "getV3Version()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "fund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getConversionRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestRoundData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getV3Version",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConversionRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getV3Version",
    data: BytesLike
  ): Result;

  events: {};
}

export class V3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: V3Interface;

  functions: {
    fund(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getConversionRate(
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLatestRoundData(overrides?: CallOverrides): Promise<[BigNumber]>;

    getV3Version(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  fund(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getConversionRate(
    ethAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLatestRoundData(overrides?: CallOverrides): Promise<BigNumber>;

  getV3Version(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    fund(overrides?: CallOverrides): Promise<void>;

    getConversionRate(
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLatestRoundData(overrides?: CallOverrides): Promise<BigNumber>;

    getV3Version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    fund(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getConversionRate(
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLatestRoundData(overrides?: CallOverrides): Promise<BigNumber>;

    getV3Version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    fund(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getConversionRate(
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLatestRoundData(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getV3Version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
