import type { NextPage } from "next";
import Head from "next/head";

import { Form, Misc } from "../modules/design";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Form />
      <Misc />
    </div>
  );
};

export default Home;
