import { Box, Center, Flex, Heading, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

import Navbar from "../modules/common/navbar";

const Home: NextPage = () => {
  // https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui
  return (
    <Box>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Center mt={"20rem"}>
        <Heading>Welcome to H World</Heading>
      </Center>
    </Box>
  );
};

export default Home;
